# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='username',
        ),
    ]
