# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20160917_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='past',
            field=models.BooleanField(default=True),
        ),
    ]
